---
- platform: template
  sensors:
    easyplus:
      friendly_name: "Easyplus Master"
      entity_id: sensor.easyplus_boiler, sensor.easyplus_kitchen, sensor.easyplus_was
      device_class: power
      value_template: >-
        {% if is_state('sensor.easyplus_boiler', 'on') %}
          on
        {% elif is_state('sensor.easyplus_kitchen', 'on') %}
          on
        {% elif is_state('sensor.easyplus_was', 'on') %}
          on
        {% else %}
          off
        {% endif %}

- platform: template
  sensors:
    easyplus_away:
      friendly_name: "Easyplus Master Away"
      entity_id: sensor.easyplus_was, group.floradix
      device_class: power
      value_template: >-
        {% if is_state('group.floradix', 'home') %}
          on
        {% elif is_state('sensor.easyplus', 'on') %}
          on
        {% else %}
          off
        {% endif %}

- platform: template
  sensors:
    easyplus_boiler:
      friendly_name: "Boiler Master"
      entity_id: input_boolean.easyplus_boiler_shower, input_boolean.easyplus_boiler_heating
      device_class: power
      value_template: >-
        {% if is_state('input_boolean.easyplus_boiler_shower', 'on') %}
          on
        {% elif is_state('input_boolean.easyplus_boiler_heating', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      icon_template: >-
        {% if is_state('input_boolean.easyplus_boiler_shower', 'on') %}
           mdi:shower-head
        {% elif is_state('input_boolean.easyplus_boiler_heating', 'on') %}
            mdi:fan
        {% else %}
            mdi:close-circle-outline
        {% endif %}

- platform: template
  sensors:
    easyplus_boiler_heating:
      friendly_name: "Heating Master"
      entity_id: input_boolean.easyplus_boiler_heating_1h_eetkamer,input_boolean.easyplus_boiler_heating_1h_floradix,input_boolean.easyplus_boiler_heating_1h_living,input_boolean.easyplus_boiler_heating_1h_sara,input_boolean.easyplus_boiler_heating_1h_yassin,input_boolean.easyplus_boiler_heating_2h_eetkamer,input_boolean.easyplus_boiler_heating_2h_floradix,input_boolean.easyplus_boiler_heating_2h_living,input_boolean.easyplus_boiler_heating_2h_sara,input_boolean.easyplus_boiler_heating_2h_yassin
      device_class: power
      value_template: >-
        {% if 'on' in states.input_boolean.easyplus_boiler_heating_1h_eetkamer.state %}
          on
        {% elif 'on' in states.input_boolean.easyplus_boiler_heating_1h_floradix.state %}
          on
        {% elif 'on' in states.input_boolean.easyplus_boiler_heating_1h_living.state %}
          on
        {% elif 'on' in states.input_boolean.easyplus_boiler_heating_1h_sara.state %}
          on
        {% elif 'on' in states.input_boolean.easyplus_boiler_heating_1h_yassin.state %}
          on
        {% elif 'on' in states.input_boolean.easyplus_boiler_heating_2h_eetkamer.state %}
          on
        {% elif 'on' in states.input_boolean.easyplus_boiler_heating_2h_floradix.state %}
          on
        {% elif 'on' in states.input_boolean.easyplus_boiler_heating_2h_living.state %}
          on
        {% elif 'on' in states.input_boolean.easyplus_boiler_heating_2h_sara.state %}
          on
        {% elif 'on' in states.input_boolean.easyplus_boiler_heating_2h_yassin.state %}
          on
        {% else %}
          off
        {% endif %}

- platform: template
  sensors:
    easyplus_was:
      friendly_name: "Was"
      entity_id: switch.stp_berging_droogkast,switch.stp_berging_wasmachine
      device_class: power
      value_template: >-
        {% if 'on' in states.switch.stp_berging_wasmachine.state %}
          on
        {% elif 'on' in states.switch.stp_berging_droogkast.state %}
          on
        {% else %}
          off
        {% endif %}
      icon_template: >-
        {% if 'on' in states.switch.stp_berging_wasmachine.state %}
           mdi:washing-machine
        {% elif 'on' in states.switch.stp_berging_droogkast.state %}
            mdi:tumble-dryer
        {% else %}
            mdi:close-circle-outline
        {% endif %}

- platform: template
  sensors:
    easyplus_kitchen:
      friendly_name: "Kitchen"
      entity_id: switch.stp_keuken_vaatwasser, switch.stp_keuken_commander,switch.stp_keuken_espresso,switch.stp_keuken_oven,switch.stp_keuken_water,switch.stp_keuken_microgolf,switch.stp_eetkamer_tv
      device_class: power
      value_template: >-
         {% if 'on' in states.switch.stp_keuken_vaatwasser.state %}
          on
         {% elif 'on' in states.switch.stp_keuken_microgolf.state %}
          on
         {% elif 'on' in states.switch.stp_eetkamer_tv.state %}
          on
         {% elif 'on' in states.switch.stp_keuken_oven.state %}
          on
         {% elif 'on' in states.switch.stp_keuken_water.state %}
          on
         {% elif 'on' in states.switch.stp_keuken_espresso.state %}
          on
         {% elif 'on' in states.switch.stp_keuken_commander.state %}
          on
         {% else %}
          off
         {% endif %}
      icon_template: >-
        {% if 'on' in states.switch.stp_keuken_vaatwasser.state %}
          mdi:dishwasher
        {% elif 'on' in states.switch.stp_keuken_micrgolf.state %}
          mdi:microwave
        {% elif 'on' in states.switch.stp_keuken_oven.state %}
          mdi:toaster-oven
        {% elif 'on' in states.switch.stp_keuken_water.state %}
          mdi:water-pump
        {% elif 'on' in states.switch.stp_keuken_espresso.state %}
          mdi:coffee
        {% elif 'on' in states.switch.stp_eetkamer_tv.state %}
          mdi:television-box
        {% elif 'on' in states.switch.stp_keuken_commander.state %}
          mdi:food
        {% else %}
          mdi:close-circle-outline
        {% endif %}
