---
- platform: template # level 1
  sensors:
    easyplus:
      friendly_name: "Easyplus Master"
      entity_id: sensor.easyplus_boiler, sensor.easyplus_cleaning
      device_class: power
      value_template: >-
        {% if 'on' in states.sensor.easyplus_boiler.state %} #includes shower + heating zones
          on
        {% elif 'on' in states.sensor.easyplus_cleaning.state %} #includes dishwasher, wasmachine & dryer
          on
        {% else %}
          off
        {% endif %}

- platform: template # level 2
  sensors:
    easyplus_boiler:
      friendly_name: "Boiler Master"
      entity_id: input_boolean.easyplus_boiler_shower, input_boolean.easyplus_boiler_heating
      device_class: power
      value_template: >-
        {% if 'on' in states.input_boolean.easyplus_boiler_shower.state %}
          on
        {% elif 'on' in states.input_boolean.easyplus_boiler_heating.state %}
          on
        {% else %}
          off
        {% endif %}

- platform: template  # level 3
  sensors:
    easyplus_boiler_heating:
      friendly_name: "Heating Master"
      entity_id: input_boolean.easyplus_boiler_heating_1h_eetkamer,input_boolean.easyplus_boiler_heating_1h_floradix,input_boolean.easyplus_boiler_heating_1h_living,input_boolean.easyplus_boiler_heating_1h_sara,input_boolean.easyplus_boiler_heating_1h_yassin,input_boolean.easyplus_boiler_heating_2h_eetkamer,input_boolean.easyplus_boiler_heating_2h_floradix,input_boolean.easyplus_boiler_heating_2h_living,input_boolean.easyplus_boiler_heating_2h_sara,input_boolean.easyplus_boiler_heating_2h_yassin
      device_class: power
      value_template: >-
        {% if 'on' in states.input_boolean.easyplus_boiler_heating_1h_eetkamer.state %}
          on
        {% elif 'on' in states.input_boolean.easyplus_boiler_heating_1h_floradix.state %}
          on
        {% elif 'on' in states.input_boolean.easyplus_boiler_heating_1h_living.state %}
          on
        {% elif 'on' in states.input_boolean.easyplus_boiler_heating_1h_sara.state %}
          on
        {% elif 'on' in states.input_boolean.easyplus_boiler_heating_1h_yassin.state %}
          on
        {% elif 'on' in states.input_boolean.easyplus_boiler_heating_2h_eetkamer.state %}
          on
        {% elif 'on' in states.input_boolean.easyplus_boiler_heating_2h_floradix.state %}
          on
        {% elif 'on' in states.input_boolean.easyplus_boiler_heating_2h_living.state %}
          on
        {% elif 'on' in states.input_boolean.easyplus_boiler_heating_2h_sara.state %}
          on
        {% elif 'on' in states.input_boolean.easyplus_boiler_heating_2h_yassin.state %}
          on
        {% else %}
          off
        {% endif %}

- platform: template
  sensors:
    easyplus_cleaning:
      friendly_name: "Cleaning Master"
      entity_id: switch.stp_keuken_vaatwasser,switch.stp_berging_droogkast,switch.stp_berging_wasmachine
      device_class: power
      value_template: >-
        {% if 'on' in states.switch.stp_keuken_vaatwasser.state %}
          on
        {% elif 'on' in states.switch.stp_berging_wasmachine.state %}
          on
        {% elif 'on' in states.switch.stp_berging_droogkast.state %}
          on
        {% else %}
          off
        {% endif %}
