---
- platform: mqtt
  name: Smappee power
  state_topic: "servicelocation/5796cd51-d672-11e7-ac58-022d286959f5/realtime"
  unit_of_measurement: "W"
  icon: "mdi:power-plug"
  value_template: "{{ value_json.totalPower }}"

- platform: mqtt
  name: Smappee usage today
  state_topic: "servicelocation/5796cd51-d672-11e7-ac58-022d286959f5/realtime"
  unit_of_measurement: "kWh"
  icon: "mdi:power-plug"
  value_template: "{{ (value_json.totalImportEnergy | multiply(0.0000001)) | round(2) }}"

- platform: mqtt
  name: Smappee reactive power
  state_topic: "servicelocation/5796cd51-d672-11e7-ac58-022d286959f5/realtime"
  unit_of_measurement: "W"
  icon: "mdi:power-plug"
  value_template: "{{ value_json.totalReactivePower }}"

- platform: mqtt
  name: Smappee voltage
  state_topic: "servicelocation/5796cd51-d672-11e7-ac58-022d286959f5/realtime"
  unit_of_measurement: "V"
  icon: "mdi:power-plug"
  value_template: "{{ value_json.voltages[0].voltage }}"

- platform: mqtt
  name: Smappee always on
  state_topic: "servicelocation/5796cd51-d672-11e7-ac58-022d286959f5/aggregated"
  unit_of_measurement: "W"
  icon: "mdi:power-plug"
  value_template: "{{ (value_json.intervalDatas[0].alwaysOn | multiply(0.001)) | round(2) }}"

- platform: mqtt
  name: Smappee average RMS Voltage
  state_topic: "servicelocation/5796cd51-d672-11e7-ac58-022d286959f5/aggregated"
  unit_of_measurement: "V"
  icon: "mdi:power-plug"
  value_template: "{{ (value_json.intervalDatas[0].averageRMSVoltage | multiply(0.1)) | round(2) }}"

- platform: mqtt
  name: Smappee server power
  state_topic: "servicelocation/5796cd51-d672-11e7-ac58-022d286959f5/aggregatedSwitch"
  unit_of_measurement: "W"
  icon: "mdi:power-plug"
  value_template: "{{ (value_json.switchIntervalDatas[0].activePower | multiply(0.001)) | round(2) }}"

- platform: mqtt
  name: Smappee xxx power
  state_topic: "servicelocation/5796cd51-d672-11e7-ac58-022d286959f5/aggregatedSwitch"
  unit_of_measurement: "W"
  icon: "mdi:power-plug"
  value_template: "{{ (value_json.switchIntervalDatas[1].activePower | multiply(0.001)) | round(2) }}"
