kind: pipeline
name: default

steps:
  - name: test
    image: homeassistant/home-assistant:latest
    commands:
      - mkdir -p fake_directory
      - touch fake_directory/data.log
      - touch fake_directory/cert.log
      - echo "10" > fake_directory/cert.log
      - touch fake_directory/cert_eu.log
      - echo "10" > fake_directory/cert_eu.log
      - mv secrets_redacted.yaml secrets.yaml
      - hass -c . --script check_config
      # - echo "Cleaning up custom components"
      # - rm -rf ./custom_components/here_travel_time

  # - name: deploy
  #   image: appleboy/drone-scp
  #   settings:
  #     host: <your-ip-address>
  #     username:
  #       from_secret: ssh_username
  #     password:
  #       from_secret: ssh_password
  #     port: 22
  #     target: /share/VM/homeautomation/home-assistant
  #     source:
  #        - .

  # - name: update
  #   image: appleboy/drone-ssh
  #   settings:
  #     host: <your-ip-address>
  #     username:
  #       from_secret: ssh_username
  #     password:
  #       from_secret: ssh_password
  #     port: 22
  #     script:
  #       - /share/CACHEDEV1_DATA/.qpkg/container-station/bin/docker restart homeassistant