kind: pipeline
name: default

steps:
  - name: test
    image: homeassistant/home-assistant:latest
    commands:
      # - echo "Downloading here_travel_time component"
      # - wget -O /tmp/here.zip https://github.com/eifinger/here_travel_time/archive/master.zip
      # - unzip /tmp/here.zip 'here_travel_time-master/custom_components/here_travel_time/*' -d /tmp/
      # - cp -R /tmp/here_travel_time-master/custom_components/here_travel_time ./custom_components/
      - hass -c . --script check_config
      # - echo "Cleaning up custom components"
      # - rm -rf ./custom_components/here_travel_time
  
  # - name: deploy
  #   image: appleboy/drone-scp
  #   settings:
  #     host: <your-ip-address>
  #     username:
  #       from_secret: ssh_username
  #     password:
  #       from_secret: ssh_password
  #     port: 22
  #     target: /share/VM/homeautomation/home-assistant
  #     source:
  #        - .
  
  # - name: update
  #   image: appleboy/drone-ssh
  #   settings:
  #     host: <your-ip-address>
  #     username:
  #       from_secret: ssh_username
  #     password:
  #       from_secret: ssh_password
  #     port: 22
  #     script:
  #       - /share/CACHEDEV1_DATA/.qpkg/container-station/bin/docker restart homeassistant