---
# dist: xenial
# language: python
# cache: pip
# python:
#   - "3.7.3"
# before_install:
#   - mkdir -p fake_directory
#   - touch fake_directory/data.log
#   - touch fake_directory/cert.log
#   - echo "10" > fake_directory/cert.log
#   - touch fake_directory/cert_eu.log
#   - echo "10" > fake_directory/cert_eu.log
#   - mv secrets_redacted.yaml secrets.yaml
# install:
#   - pip3 install homeassistant
#   - hass --version
# script:
#   - hass -c . --script check_config
# after_script:
#   - bash ./telegram_notification.sh
# notifications:
#   webhooks: https://fathomless-fjord-24024.herokuapp.com/notify?secret=elradix_hass


# stages:
#   - dev
#   - rc
#   - prod


dist: xenial
language: python
cache: pip
python:
  - "3.7.3"
before_install:
  - mkdir -p fake_directory
  - touch fake_directory/data.log
  - touch fake_directory/cert.log
  - echo "10" > fake_directory/cert.log
  - touch fake_directory/cert_eu.log
  - echo "10" > fake_directory/cert_eu.log
  - mv secrets_redacted.yaml secrets.yaml

install:
  - pip3 install homeassistant
  - hass --version

jobs:
  include:
    - stage: HA Test
      script:
        - hass -c . --script check_config
      after_script:
        - bash ./telegram_notification.sh
      notifications:
        webhooks: https://fathomless-fjord-24024.herokuapp.com/notify?secret=elradix_hass

