---
# dist: xenial
# language: python
# cache: pip
# python:
#   - "3.7.3"
# before_install:
#   - mkdir -p fake_directory
#   - touch fake_directory/data.log
#   - touch fake_directory/cert.log
#   - echo "10" > fake_directory/cert.log
#   - touch fake_directory/cert_eu.log
#   - echo "10" > fake_directory/cert_eu.log
#   - mv secrets_redacted.yaml secrets.yaml
# install:
#   - pip3 install homeassistant
#   - hass --version
# script:
#   - hass -c . --script check_config
# after_script:
#   - bash ./telegram_notification.sh
# notifications:
#   webhooks: https://fathomless-fjord-24024.herokuapp.com/notify?secret=elradix_hass


# stages:
#   - PROD
#   - DEV


# dist: xenial
# language: python
# cache: pip
# python:
#   - "3.7.3"


# # install:
# #   - pip3 install homeassistant
# #   - hass --version

# jobs:
#   include:
#     - stage: PROD
#       before_install:
#         - mkdir -p fake_directory
#         - touch fake_directory/data.log
#         - touch fake_directory/cert.log
#         - echo "10" > fake_directory/cert.log
#         - touch fake_directory/cert_eu.log
#         - echo "10" > fake_directory/cert_eu.log
#         - mv secrets_redacted.yaml secrets.yaml
#       install:
#         - pip3 install homeassistant
#         - hass --version
#       script:
#         - hass -c . --script check_config

#     - stage: DEV
#       before_install:
#         - mkdir -p fake_directory
#         - touch fake_directory/data.log
#         - touch fake_directory/cert.log
#         - echo "10" > fake_directory/cert.log
#         - touch fake_directory/cert_eu.log
#         - echo "10" > fake_directory/cert_eu.log
#         - mv secrets_redacted.yaml secrets.yaml
#       install:
#         - pip3 install --pre --upgrade homeassistant
#         - hass --version
#       script:
#         - hass -c . --script check_config
#       after_script:
#         - bash ./telegram_notification.sh
#       notifications:
#         webhooks: https://fathomless-fjord-24024.herokuapp.com/notify?secret=elradix_hass




language: python
python:
  - 3.7.3
env:
  - BUILD=stable
  - BUILD=beta
  - BUILD=dev
matrix:
  allow_failures:
    - python: 3.7.3
      env: BUILD=dev

before_install:
  - mv tests/fake_secrets.yaml secrets.yaml
  - mkdir -p fake_directory
  - touch fake_directory/data.log
  - touch fake_directory/cert.log
  - echo "10" > fake_directory/cert.log
  - touch fake_directory/cert_eu.log
  - echo "10" > fake_directory/cert_eu.log
  - mv secrets_redacted.yaml secrets.yaml
install:
  - if [ $BUILD == "beta" ]; then
      pip3 install --pre homeassistant;
    elif [ $BUILD == "dev" ]; then
      pip3 install git+git://github.com/home-assistant/home-assistant.git@dev;
    else
      pip3 install homeassistant;
    fi
script:
  - hass -c . --script check_config
after_script:
  - bash ./telegram_notification.sh
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify?secret=elradix_hass