version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    #parallelism: 4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Check config
          command: |
            mv secrets_redacted.yaml secrets.yaml
            mkdir fake_directory
            touch fake_directory/data.log
            touch fake_directory/cert.log
            touch fake_directory/cert_eu.log  
            echo "10" > fake_directory/cert.log
            echo "10" > fake_directory/cert_eu.log
            python3.6 -m venv .
            source bin/activate
            pip install --upgrade pip
            pip3 install homeassistant
            hass -c . --script check_config
            hass --version


workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build

