---
version: 2.1
jobs:
  prod:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: HA Prod - Check config
          command: |
            mv secrets_redacted.yaml secrets.yaml
            mkdir fake_directory
            touch fake_directory/data.log
            touch fake_directory/cert.log
            touch fake_directory/cert_eu.log
            echo "10" > fake_directory/cert.log
            echo "10" > fake_directory/cert_eu.log
            python3.7 -m venv .
            source bin/activate
            pip install --upgrade pip
            pip3 install homeassistant
            hass -c . --script check_config #--info all
            hass --version

  dev:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: HA Beta - Check config
          command: |
            mv secrets_redacted.yaml secrets.yaml
            mkdir fake_directory
            touch fake_directory/data.log
            touch fake_directory/cert.log
            touch fake_directory/cert_eu.log
            echo "10" > fake_directory/cert.log
            echo "10" > fake_directory/cert_eu.log
            python3.7 -m venv .
            source bin/activate
            pip install --upgrade pip
            pip3 install --pre --upgrade homeassistant
            hass -c . --script check_config #--info all
            hass --version

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - prod
      - dev