---
timer:
  dish:
    duration: '00:45:00'
  was:
    duration: '02:00:00'
  dryer:
    duration: '02:30:00'

script:
  turn_on_dryer:
    sequence:
    - service: homeassistant.turn_on
      entity_id: switch.stp_berging_droogkast
    - service: timer.start
      entity_id: timer.dryer
    - delay:
        seconds: 4
    - service: notify.dageraad
      data_template:
        message: 'dryer program: {{states.switch.stp_berging_droogkast.state}}'

  turn_off_dryer:
    sequence:
    - service: homeassistant.turn_off
      entity_id: switch.stp_berging_droogkast
    - service: timer.cancel
      entity_id: timer.dryer
    - delay:
        seconds: 4
    - service: notify.dageraad
      data_template:
        message: 'was program: {{states.switch.stp_berging_droogkast.state}}'

  turn_on_was:
    sequence:
    - service: homeassistant.turn_on
      entity_id: switch.stp_berging_wasmachine
    - service: timer.start
      entity_id: timer.was
    - delay:
        seconds: 4
    - service: notify.dageraad
      data_template:
        message: 'was program: {{states.switch.stp_berging_wasmachine.state}}'

  turn_off_was:
    sequence:
    - service: homeassistant.turn_off
      entity_id: switch.stp_berging_wasmachine
    - service: timer.cancel
      entity_id: timer.was
    - delay:
        seconds: 4
    - service: notify.dageraad
      data_template:
        message: 'was program: {{states.switch.stp_berging_wasmachine.state}}'

  turn_on_dish:
    sequence:
    - service: homeassistant.turn_on
      entity_id: switch.stp_keuken_vaatwasser, switch.stp_keuken_commander
    - service: timer.start
      entity_id: timer.dish
    - delay:
        seconds: 4
    - service: notify.dageraad
      data_template:
        message: 'dish program: {{states.switch.stp_keuken_vaatwasser.state}}/{{states.switch.stp_keuken_commander.state}}'

  turn_off_dish:
    sequence:
    - service: homeassistant.turn_off
      entity_id: switch.stp_keuken_vaatwasser, switch.stp_keuken_commander
    - service: timer.cancel
      entity_id: timer.dish
    - delay:
        seconds: 4
    - service: notify.dageraad
      data_template:
        message: 'dish program: {{states.switch.stp_keuken_vaatwasser.state}}/{{states.switch.stp_keuken_commander.state}}'

  turn_on_away:
    sequence:
    - service: script.lights
    - service: notify.dageraad
      data:
        message: "away mode, lights off"
    - delay:
        seconds: 30
    - service: script.switches
    - service: notify.dageraad
      data:
        message: "away mode, switches off"
    - delay:
        seconds: 30
    - service: switch.turn_off
      entity_id: switch.easyplus
    - service: notify.dageraad
      data:
        message: "away mode, easyplus off"

automation:

  - id: start_scenes
    initial_state: 'true'
    alias: 'start scenes rf button'
    trigger:
    - platform: state
      entity_id: binary_sensor.rf_btn_1c60b1, binary_sensor.rf_btn_4ffd01, binary_sensor.rf_btn_45a081
      from: 'off'
      to: 'on'
    action:
    - service: python_script.easyplus
      data_template:
        script_id: "turn_on_{{ trigger.to_state.name }}"

  - id: stop_scenes
    initial_state: 'true'
    alias: 'stop scenes manual'
    trigger:
    - platform: state
      entity_id: switch.stp_berging_droogkast,switch.stp_berging_wasmachine,switch.stp_keuken_vaatwasser,switch.stp_keuken_commander
      from: 'on'
      to: 'off'
    action:
    - service_template: "script.turn_off_{{ trigger.to_state.name }}"

  - id: timers_stop
    initial_state: 'true'
    alias: 'timers stop'
    trigger:
    - platform: event
      event_type: timer.finished
    condition:
      condition: template
      value_template: >
        {{ trigger.event.data.entity_id in ['timer.dish',
                                            'timer.was',
                                            'timer.dryer'] }}
    action:
    - service: homeassistant.turn_on
      data_template:
        entity_id: >-
          {% if trigger.event.data.entity_id == 'timer.dish' %}
            script.turn_off_dish
          {% elif trigger.event.data.entity_id == 'timer.was' %}
            script.turn_off_was
          {% else %}
            script.turn_off_dryer
          {% endif %}
    - service: notify.dageraad
      data_template:
        message: 'program: {{trigger.event.data.entity_id}} completed'

  - id: away_modus
    initial_state: 'true'
    alias: away modus
    trigger:
    - platform: state
      entity_id: sensor.easyplus_away
      to: 'on'
      for:
        minutes: 3
    action:
    # - service: homeassistant.turn_off
    #   entity_id: switch.easyplus
    # - delay:
    #     seconds: 4
    - service: notify.dageraad
      data_template:
        message: 'Away modus: {{states.switch.easyplus.state}}'
