---
group:
 easyplus_sensors:
    name: Easyplus
    icon: mdi:flash
    entities:
      - sensor.easyplus
      - sensor.easyplus_boiler
      - sensor.easyplus_kitchen
      - sensor.easyplus_was
      - sensor.easyplus_away

timer:
  dish:
    duration: '00:40:00'
    icon: mdi:dishwasher
  was:
    duration: '02:00:00'
    icon: mdi:washing-machine
  dryer:
    duration: '02:30:00'
    icon: mdi:tumble-dryer
  espresso:
    duration: '00:15:00'
    icon: mdi:coffee
  water:
    duration: '01:00:00'
    icon: mdi:water-pump
  oven:
    duration: '02:00:00'
    icon: mdi:toaster-oven
  microgolf:
    duration: '00:30:00'
    icon: mdi:microwave
  samsung:
    duration: '02:00:00'
    icon: mdi:television-box

script:

  turn_on_samsung:
    sequence:
    - service: homeassistant.turn_on
      entity_id: switch.stp_eetkamer_tv
    - service: timer.start
      data_template:
         entity_id: '{{ timer }}'
    - delay:
        seconds: 5
    - service: notify.dageraad
      data_template:
        message: '{{ friendly_name }} program: {{state}}'
  turn_off_samsung:
    sequence:
    - service: homeassistant.turn_off
      entity_id: switch.stp_eetkamer_tv
    - service: timer.cancel
      data_template:
         entity_id: '{{ timer }}'
    - delay:
        seconds: 5
    - service: notify.dageraad
      data_template:
        message: '{{ friendly_name }} program: {{state}}'

  turn_on_microgolf:
    sequence:
    - service: homeassistant.turn_on
      entity_id: switch.stp_keuken_microwave
    - service: timer.start
      data_template:
         entity_id: '{{ timer }}'
    - delay:
        seconds: 5
    - service: notify.telegram
      data_template:
        message: '{{ friendly_name }} program: {{state}}'

  turn_off_microgolf:
    sequence:
    - service: homeassistant.turn_off
      entity_id: switch.stp_keuken_microwave
    - service: timer.start
      data_template:
         entity_id: '{{ timer }}'
    - delay:
        seconds: 5
    - service: notify.telegram
      data_template:
        message: '{{ friendly_name }} program: {{state}}'

  turn_on_oven:
    sequence:
    - service: homeassistant.turn_on
      entity_id: switch.stp_keuken_microwave
    - service: timer.start
      data_template:
         entity_id: '{{ timer }}'
    - delay:
        seconds: 5
    - service: notify.telegram
      data_template:
        message: '{{ friendly_name }} program: {{state}}'

  turn_off_oven:
    sequence:
    - service: homeassistant.turn_off
      entity_id: switch.stp_keuken_oven
    - service: timer.start
      data_template:
         entity_id: '{{ timer }}'
    - delay:
        seconds: 4
    - service: notify.telegram
      data_template:
        message: '{{ friendly_name }} program: {{state}}'

  turn_on_commander:
    sequence:
    - service: homeassistant.turn_on
      entity_id: switch.stp_keuken_commander
    - service: timer.start
      data_template:
         entity_id: '{{ timer }}'
    - delay:
        seconds: 4
    - service: notify.telegram
      data_template:
        message: '{{ friendly_name }} program: {{state}}'

  turn_off_commander:
    sequence:
    - service: homeassistant.turn_off
      entity_id: switch.stp_keuken_commander
    - service: timer.start
      data_template:
         entity_id: '{{ timer }}'
    - delay:
        seconds: 4
    - service: notify.telegram
      data_template:
        message: '{{ friendly_name }} program: {{state}}'

  turn_on_waterkoker:
    sequence:
    - service: homeassistant.turn_on
      entity_id: switch.stp_keuken_water
    - service: timer.start
      data_template:
         entity_id: '{{ timer }}'
    - delay:
        seconds: 4
    - service: notify.telegram
      data_template:
        message: '{{ friendly_name }} program: {{state}}'

  turn_off_waterkoker:
    sequence:
    - service: homeassistant.turn_off
      entity_id: switch.stp_keuken_water
    - service: timer.start
      data_template:
         entity_id: '{{ timer }}'
    - delay:
        seconds: 4
    - service: notify.telegram
      data_template:
        message: '{{ friendly_name }} program: {{state}}'

  turn_on_espresso:
    sequence:
    - service: homeassistant.turn_on
      entity_id: switch.stp_keuken_espresso
    - service: homeassistant.turn_on
      entity_id: switch.stp_keuken_microwave
    - service: timer.start
      data_template:
         entity_id: '{{ timer }}'
    - delay:
        seconds: 5
    - service: notify.dageraad
      data_template:
        message: '{{ friendly_name }} program: {{state}}'

  turn_off_espresso:
    sequence:
    - service: homeassistant.turn_off
      entity_id: switch.stp_keuken_espresso
    - service: homeassistant.turn_on
      entity_id: switch.stp_keuken_microwave
    - service: timer.cancel
      data_template:
         entity_id: '{{ timer }}'
    - service: timer.cancel
      entity_id: timer.microgolf
    - delay:
        seconds: 5
    - service: notify.dageraad
      data_template:
        message: '{{ friendly_name }} program: {{state}}'

  turn_on_dryer:
    sequence:
    - service: homeassistant.turn_on
      entity_id: switch.stp_berging_droogkast
    - service: timer.start
      data_template:
         entity_id: '{{ timer }}'
    - delay:
        seconds: 4
    - service: notify.telegram
      data_template:
        message: '{{ friendly_name }} program: {{state}}'

  turn_off_dryer:
    sequence:
    - service: homeassistant.turn_off
      entity_id: switch.stp_berging_droogkast
    - service: timer.start
      data_template:
         entity_id: '{{ timer }}'
    - delay:
        seconds: 4
    - service: notify.telegram
      data_template:
        message: '{{ friendly_name }} program: {{state}}'

  turn_on_was:
    sequence:
    - service: homeassistant.turn_on
      entity_id: switch.stp_berging_wasmachine
    - service: timer.start
      data_template:
         entity_id: '{{ timer }}'
    - delay:
        seconds: 4
    - service: notify.telegram
      data_template:
        message: '{{ friendly_name }} program: {{state}}'

  turn_off_was:
    sequence:
    - service: homeassistant.turn_on
      entity_id: switch.stp_berging_wasmachine
    - service: timer.start
      data_template:
         entity_id: '{{ timer }}'
    - delay:
        seconds: 4
    - service: notify.telegram
      data_template:
        message: '{{ friendly_name }} program: {{state}}'

  turn_on_dish:
    sequence:
    - service: homeassistant.turn_on
      entity_id: switch.stp_keuken_vaatwasser
    - service: homeassistant.turn_on
      entity_id: switch.stp_keuken_commander
    - service: timer.start
      data_template:
         entity_id: '{{ timer }}'
    - delay:
        seconds: 5
    - service: notify.dageraad
      data_template:
        message: '{{ friendly_name }} program: {{state}}'

  turn_off_dish:
    sequence:
    - service: homeassistant.turn_off
      entity_id: switch.stp_keuken_vaatwasser
    - service: homeassistant.turn_off
      entity_id: switch.stp_keuken_commander
    - service: timer.cancel
      data_template:
         entity_id: '{{ timer }}'
    - delay:
        seconds: 5
    - service: notify.dageraad
      data_template:
        message: '{{ friendly_name }} program: {{state}}'

  scene_completed:
    sequence:
    - service: script.lights
    - service: notify.dageraad
      data:
        message: "scences completed, lights off"
    - delay:
        seconds: 30
    - service: script.switches
    - service: notify.dageraad
      data:
        message: "scences completed,  switches off"
    - delay:
        seconds: 30
    - service: switch.turn_off
      entity_id: switch.easyplus
    - service: notify.dageraad
      data:
        message: "scences completed, easyplus off"

automation:

  - id: start_scenes
    initial_state: 'true'
    alias: 'start scenes'
    trigger:
    - platform: state
      entity_id: switch.stp_eetkamer_tv,switch.stp_keuken_oven,binary_sensor.rf_btn_1c60b1, binary_sensor.rf_btn_4ffd01, binary_sensor.rf_btn_45a081,binary_sensor.rf_btn_793401,binary_sensor.rf_btn_909601,switch.stp_berging_droogkast,switch.stp_berging_wasmachine,switch.stp_keuken_vaatwasser,switch.stp_keuken_commander,switch.stp_keuken_espresso,switch.stp_keuken_water
      from: 'off'
      to: 'on'
    action:
    - service: python_script.easyplus
      data_template:
        script_id: "turn_on_{{ trigger.to_state.name}}"
        timer: 'timer.{{ trigger.to_state.attributes.friendly_name }}'
        friendly_name: '{{ trigger.to_state.attributes.friendly_name }}'
        state: '{{ trigger.to_state.state }}'

  - id: start_scenes_switchx
    initial_state: 'true'
    alias: 'start scenes switchx'
    trigger:
    - platform: state
      entity_id: switch.stp_keuken_microwave
      from: 'off'
      to: 'on'
    action:
    - service_template: 'script.{{ trigger.to_state.name }}'
    - service: python_script.easyplus_switch
      data_template:
        entity_id: "{{ trigger.to_state.entity_id }}"
        timer: 'timer.{{ trigger.to_state.attributes.friendly_name }}'
        friendly_name: '{{ trigger.to_state.attributes.friendly_name }}'
        state: '{{ trigger.to_state.state }}'

       # entity: '{{ trigger.to_state.entity_id }}'
      #  entity: '{{ trigger.to_state.entity_id }}'

    # - service: python_script.easyplus_switch
    #   data:
    #     entity_id: switch.stp_keuken_microwave
    # - service: script.turn_on_kitchen
    #   data_template:
    #     timer: 'timer.{{ trigger.to_state.attributes.friendly_name }}'
    #     friendly_name: '{{ trigger.to_state.attributes.friendly_name }}'
    #     state: '{{ trigger.to_state.state }}'
    # # - service: python_script.easyplus_switch
    # #   data_template:
    # #     entity_id: "{{ trigger.to_state.entity_id }}"

  - id: stop_scenes
    initial_state: 'true'
    alias: 'stop scenes manual'
    trigger:
    - platform: state
      entity_id: switch.stp_eetkamer_tv,switch.stp_keuken_microwave,switch.stp_keuken_oven,switch.stp_berging_droogkast,switch.stp_berging_wasmachine,switch.stp_keuken_vaatwasser,switch.stp_keuken_commander,switch.stp_keuken_espresso,switch.stp_keuken_water
      from: 'on'
      to: 'off'
    action:
    - service_template: "script.turn_off_{{ trigger.to_state.name }}"
      data_template:
        timer: 'timer.{{ trigger.to_state.attributes.friendly_name }}'
        friendly_name: '{{ trigger.to_state.attributes.friendly_name }}'
        state: '{{ trigger.to_state.state }}'


  - id: timers_stop
    initial_state: 'true'
    alias: 'timers stop'
    trigger:
    - platform: event
      event_type: timer.finished
    condition:
      condition: template
      value_template: >
        {{ trigger.event.data.entity_id in ['timer.dish',
                                            'timer.was',
                                            'timer.dryer',
                                            'timer.espresso',
                                            'timer.waterkoker',
                                            'timer.samsung',
                                            'timer.oven',
                                            'timer.microgolf'] }}
    action:
    - service: homeassistant.turn_on
      data_template:
        entity_id: >-
          {% if trigger.event.data.entity_id == 'timer.dish' %}
            script.turn_off_dish
          {% elif trigger.event.data.entity_id == 'timer.samsung' %}
            script.turn_off_samsung
          {% elif trigger.event.data.entity_id == 'timer.microgolf' %}
            script.turn_off_microgolf
          {% elif trigger.event.data.entity_id == 'timer.oven' %}
            script.turn_off_oven
          {% elif trigger.event.data.entity_id == 'timer.waterkoker' %}
            script.turn_off_waterkoker
          {% elif trigger.event.data.entity_id == 'timer.espresso' %}
            script.turn_off_espresso
          {% elif trigger.event.data.entity_id == 'timer.was' %}
            script.turn_off_was
          {% else %}
            script.turn_off_dryer
          {% endif %}
    - service: notify.dageraad
      data_template:
        message: 'program: {{trigger.event.data.entity_id.name}} completed'

  - id: scenes completed
    initial_state: 'true'
    alias: scenes completed
    trigger:
    - platform: state
      entity_id: sensor.easyplus
      to: 'off'
      for:
        minutes: 15
    condition:
    - condition: template
      value_template: "{{ states.sensor.period_of_day.state != 'night' }}"
    action:
    - service: "script.scene_completed"
    - delay:
        seconds: 65
    - service: notify.dageraad
      data_template:
        message: 'All scenes completed, easyplus: {{states.switch.easyplus.state}}'
