# DOCKER

- platform: hadockermon
  host: !secret hadockermon_host
  port: !secret hadockermon_port
  stats: false
  prefix: docker
#  exclude:
#    - 'ha-dockermon'


- platform: hadockermon
  host: !secret hadockermon_host_nas
  port: !secret hadockermon_port_nas
  stats: false
  prefix: docker_nas
#  exclude:
#    - 'ha-dockermon'